name: BadWordBlocker
main: surva\badwordblocker\BadWordBlocker
version: 1.2.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
commands:
  chat:
    description: "Enable or disable receiving chat messages"
    usage: "/chat"
