name: BadWordBlocker
main: surva\badwordblocker\BadWordBlocker
version: 1.0.5
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
commands:
  chat:
    description: "Take chat off / on"
    usage: "/chat"
