name: BadWordBlocker
main: jjmc\BadWordBlocker\BadWordBlocker
version: 1.0.0
api: 1.0.0
author: SURVA.ml Dev Team
description: A plugin which blocks specified words in the chat
website: http://surva.ml/