name: BadWordBlocker
main: surva\BadWordBlocker\BadWordBlocker
version: 1.0.2
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
commands:
  chat:
    description: "Take chat off / on"
    usage: "/chat"