name: BadWordBlocker
main: surva\badwordblocker\BadWordBlocker
version: 1.2.5
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]

author: survanetwork
description: A chat filter which can block certain things
website: https://github.com/survanetwork/BadWordBlocker
