#  ____            ___        __            _ ____  _            _
# | __ )  __ _  __| \ \      / /__  _ __ __| | __ )| | ___   ___| | _____ _ __
# |  _ \ / _` |/ _` |\ \ /\ / / _ \| '__/ _` |  _ \| |/ _ \ / __| |/ / _ \ '__|
# | |_) | (_| | (_| | \ V  V / (_) | | | (_| | |_) | | (_) | (__|   <  __/ |
# |____/ \__,_|\__,_|  \_/\_/ \___/|_|  \__,_|____/|_|\___/ \___|_|\_\___|_|
#
# (C) 2016 by jjplaying | https://github.com/jjplaying

# List of the blocked words, seperated with a comma, example: word1,word2,word3
badwords: "fuck,shit"

# Time between chat messages
waitingtime: 02

# Messages
blockmessage: "§eYour message has been §cblocked §eby BadWordBlocker."
lastwritten: "§cPlease write something else"
timewritten: "§cPlease don't write so fast"
caps: "§cPlease turn off caps"